sudo: required
dist: xenial
language: python
cache: pip
install:
- pip install coveralls pytest pytest-cov
- pip install .
script:
- pytest --cov=ndex
after_success: coveralls
notifications:
  on_success: change
  on_failure: always
matrix:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7
env:
  global:
  - secure: OK0ntoAaZHc4T4jXKLAviC1Ifp4h0tpMS1vjGks5MKxY6a98o26REog4ebPthS+accgexqnIR6YcR9cpHTOqjlIbyOKnx3fzxtVui2p8V4BF/RoEEr2JaaNEfZbY90bXTyEsZuuplfNR3T0kg3LV9i0OH3bxcNZOzkY4o93UNrpMK8AMPQVD/4G9qF0HxVmpjF2OYOhLvxMTHwTj9YroZVx/zV9QPrTTGyLijxgkAS5a3NhhR/dZZUJ0HYy7df45N6vlBlxp5kN7D++rDW0NsGLhDAmPYLy9utQ3WA9Xr4qk9mArK9meF+zyjA785wDd0oB49RGp8DJm5tW9eTmYGuBv+UbKo5YOfNTll+ioRHoFxZISRoJTNZ84NypTyFtetziUjJBgD6/FDnkQ87r2CA1vrVjSLuPaLo1SIfCnrDLhrvYLvLKBSAQIDVR+L59WsjwWnw/SKtSFXJNBk4tHeWbiItiSqclY7LyzRspZSvtFz5vh2XPWO6gD6espKUZhtGxOX6y5wXNvFxXY6KtkfAoRvT6wgSKl/G9b4TS6A/bOD0CRFCJMUdFtlWIg1nE+4XeUWRTD89HkShpfDydZG9cA4a6Gf9HSppl5Bc8/D4yxOPlVfaiwUNDJc2eVqJvxK/pRxxVXmmJ8T26G1MknSSjRKwld+g45HRx1/6ZzxWY=
  - secure: kV56mVfuT6NBaSQ1neR6ekbstOEi5quuw0BOjS93oREZnag/5fQxVHMSfELfYlSkEYB8LyWYjzNJaFO60om5QZEUPrLiTa8GhLql2ezhnpDXXP1rHz/5co0mRxT2a844OFV0RYhUg7gDvJ4T4NTzD3r44ueDGbbT3MKBsT4GjZbZtv/RjsZNojtWW8VoOkplt8SZI99lY7IjTCM4IVTgmmicLRD1Qu+QbalF6p2RrbdVj8RojaqeZqN7tMeOJOS628Gey96tXGIy1yIIT0znOBcerFjxfo4j5/57paB03JxyL8yEHm2yvw37NR7pF/fjGT8VwNCqZukcvGvKNBe0Yx8zy0FFnB4advLj2WxrwcYaH2/EWYnBD179EiIMt2O+cNeTz6jtS+0IcEz4yLO4QjidqtpVVz7op7Z39su4gZFM6l6RKxsaYlUe3VdT3pp6ynaXciBUllVoLbilpFqp/4UdzftmR5S6idzZQQ48D1irCzpRhqsP2/2Qcye/QR6NmHuW8spwlDYVc9hsFqz774zqD4Zg4mhUr5E/5bZhxmevBxsU3PvfJf4h28Z/0YRhKyF4/4JxC5xuRm+UpXdDXfPFisFZ9DfMtdngGyqYnfVTy/kBjXn4/spE+RkApDkH9X4M4w9f/2h+Kxy0X/99LrGWS8X5dvGeNfvZs6KB7u0=
